# TREC-COVID数据集实验配置 - 测试RRF融合策略

data:
  corpus_path: "data/processed/trec-covid_corpus.jsonl"
  queries_path: "data/processed/trec-covid_queries.jsonl"
  qrels_path: "data/processed/trec-covid_qrels.tsv"
  output_dir: "data/processed/"

retrievers:
  bm25:
    enabled: true
    index_path: "checkpoints/retriever/20250713_1507_trec-covid_bm25_index.pkl"
    k1: 1.2
    b: 0.75
    top_k: 300  # 增加检索数量
    
  dense:
    enabled: true
    model_name: "sentence-transformers/all-mpnet-base-v2"  # 最强模型
    index_path: "checkpoints/retriever/20250713_1507_trec-covid_dense_index.faiss"
    embedding_dim: 768
    top_k: 300
    batch_size: 32
    max_length: 512
    
  graph:
    enabled: true
    index_path: "checkpoints/retriever/20250713_1507_trec-covid_graph_index.pkl"
    neo4j_uri: "bolt://localhost:7687"
    neo4j_user: "neo4j"
    neo4j_password: "fusionrag123"
    database: "neo4j"
    max_walk_length: 3
    entity_threshold: 2
    relation_types: ["cooccurrence", "similarity"]
    top_k: 100

# 查询分类器配置
classifier:
  enabled: true
  threshold: 0.5
  classes: ["factual", "analytical", "procedural"]
  adaptation_enabled: true
  min_samples: 10
  performance_threshold: 0.1

fusion:
  method: "rrf"  # 实验RRF融合策略
  rrf_k: 60
  top_k: 100
  # 备用权重配置
  weights:
    bm25: 0.4
    dense: 0.4
    graph: 0.2

reranker:
  enabled: false

evaluation:
  metrics: ["recall@5", "recall@10", "recall@20", "recall@50", "ndcg@10", "ndcg@20", "map", "mrr"]
  output_path: "checkpoints/logs/20250713_1507_trec-covid_experimental_eval_results.json"

system:
  device: "cpu"
  batch_size: 16
  num_threads: 8
  log_level: "INFO"
  log_path: "checkpoints/logs/20250713_1507_trec-covid_experimental_system.log"

# 配置元数据
metadata:
  created_at: "2025-07-13T15:07:00"
  dataset: "trec-covid"
  template: "experimental"
  description: "TREC-COVID数据集实验配置，测试RRF融合策略和COVID-19医疗文档检索"
  filename: "20250713_1507_trec-covid_experimental.yaml"
  experiment_focus: "RRF融合策略对COVID-19医疗查询的效果"
  expected_improvements: ["更好的排序质量", "减少位置偏差", "提高长尾查询性能"]
