classifier:
  adaptation_enabled: true
  classes:
  - factual
  - analytical
  - procedural
  enabled: true
  threshold: 0.5
data:
  corpus_path: data/processed/trec-covid_corpus.jsonl
  output_dir: data/processed/
  qrels_path: data/processed/trec-covid_qrels.tsv
  queries_path: data/processed/trec-covid_queries.jsonl
evaluation:
  metrics:
  - recall@5
  - recall@10
  - recall@20
  - recall@50
  - ndcg@10
  - ndcg@20
  - map
  - mrr
  output_path: checkpoints/logs/20250713_1508_trec-covid_high_performance_eval_results.json
fusion:
  method: weighted
  top_k: 100
  weights:
    bm25: 0.5
    dense: 0.4
    graph: 0.1
metadata:
  created_at: '2025-07-13T15:08:13.268785'
  dataset: trec-covid
  description: TREC-COVID数据集高性能配置测试
  filename: 20250713_1508_trec-covid_high_performance.yaml
  template: high_performance
retrievers:
  bm25:
    b: 0.75
    enabled: true
    index_path: checkpoints/retriever/20250713_1508_trec-covid_bm25_index.pkl
    k1: 1.2
    top_k: 300
  dense:
    batch_size: 32
    embedding_dim: 768
    enabled: true
    index_path: checkpoints/retriever/20250713_1508_trec-covid_dense_index.faiss
    model_name: sentence-transformers/all-mpnet-base-v2
    top_k: 300
  graph:
    database: neo4j
    enabled: false
    entity_threshold: 2
    index_path: checkpoints/retriever/20250713_1508_trec-covid_graph_index.pkl
    max_walk_length: 3
    neo4j_password: fusionrag123
    neo4j_uri: bolt://localhost:7687
    neo4j_user: neo4j
    top_k: 100
system:
  batch_size: 16
  device: cpu
  log_level: INFO
  log_path: checkpoints/logs/20250713_1508_trec-covid_high_performance_system.log
  num_threads: 8
