
# 高性能FusionRAG配置 - 使用最强模型和完整数据集

data:
  corpus_path: "data/processed/nfcorpus_corpus.jsonl"
  queries_path: "data/processed/nfcorpus_queries.jsonl"
  qrels_path: "data/processed/nfcorpus_qrels.tsv"
  output_dir: "data/processed/"

retrievers:
  bm25:
    enabled: true
    type: pyserini
    index_dir: "checkpoints/retriever/pyserini_bm25_multifield_index"  # 新多字段索引目录
    fields: ["title", "text"]  # 多字段检索
    k1: 0.82
    b: 0.68
    top_k: 5000  # 提升BM25候选数

  dense:
    enabled: true
    model_name: "BAAI/bge-large-en-v1.5"  # SOTA dense模型
    index_path: "checkpoints/retriever/bge_large_en_v1.5_dense_index.faiss"
    embedding_dim: 1024
    top_k: 5000  # 提升dense候选数
    batch_size: 32
    max_length: 512
    normalize_embeddings: true

  graph:
    enabled: true
    use_model_relation_extractor: true
    index_path: "checkpoints/retriever/high_performance_graph_index.pkl"
    neo4j_uri: "bolt://localhost:7687"
    neo4j_user: "neo4j"
    neo4j_password: "fusionrag123"
    database: "neo4j"
    max_walk_length: 4  # 增大游走步数，召回更远邻居
    entity_threshold: 1  # 降低阈值，召回更多实体
    relation_types: ["cooccurrence", "similarity"]
    top_k: 2000  # 图检索候选数提升

# 查询分类器配置 - 启用智能路由
classifier:
  enabled: true
  threshold: 0.5
  classes: ["factual", "analytical", "procedural"]
  adaptation_enabled: true
  min_samples: 10
  performance_threshold: 0.1

fusion:
  method: "weighted"  # 使用加权融合，更适合医疗领域
  weights:
    bm25: 0.5      # 增加BM25权重，医疗术语匹配重要
    dense: 0.4     # 语义理解
    graph: 0.1     # 关系发现
  top_k: 2000  # 融合候选数提升
  rrf_k: 60   # RRF参数

reranker:
  enabled: true
  model_name: "mixedbread-ai/mxbai-rerank-large-v1"
  top_k: 1000  # reranker候选数提升

evaluation:
  metrics: ["recall@5", "recall@10", "recall@20", "recall@50", "ndcg@10", "ndcg@20", "map", "mrr"]
  output_path: "checkpoints/logs/high_performance_eval_results.json"

system:
  device: "cpu"
  batch_size: 8   # 减小batch size提高质量
  num_threads: 8  # 增加线程数
  log_level: "INFO"
  log_path: "checkpoints/logs/20250713_1506_nfcorpus_high_performance_system.log"

# 配置元数据
metadata:
  created_at: "2025-07-13T15:06:00"
  dataset: "nfcorpus"
  template: "high_performance"
  description: "NFCorpus数据集高性能配置，使用MPNet模型+智能路由+图检索"
  filename: "20250713_1506_nfcorpus_high_performance.yaml"
