
# 高性能FusionRAG配置 - 使用最强模型和完整数据集

data:
  corpus_path: "data/processed/nfcorpus_corpus.jsonl"
  queries_path: "data/processed/nfcorpus_queries.jsonl"
  qrels_path: "data/processed/nfcorpus_qrels.tsv"
  output_dir: "data/processed/"

retrievers:
  bm25:
    enabled: true
    index_path: "checkpoints/retriever/high_performance_bm25_index.pkl"
    k1: 1.2  # 医疗文档优化参数
    b: 0.75  # 医疗文档优化参数
    top_k: 300  # 大幅增加检索数量以提高召回率

  dense:
    enabled: true
    model_name: "sentence-transformers/all-mpnet-base-v2"  # 最强的通用模型
    index_path: "checkpoints/retriever/high_performance_dense_index.faiss"
    embedding_dim: 768  # 高维度向量
    top_k: 300  # 大幅增加检索数量
    batch_size: 32   # 增加batch size提高稳定性
    max_length: 512  # 支持更长文本

  graph:
    enabled: true
    index_path: "checkpoints/retriever/high_performance_graph_index.pkl"
    neo4j_uri: "bolt://localhost:7687"
    neo4j_user: "neo4j"
    neo4j_password: "fusionrag123"
    database: "neo4j"
    max_walk_length: 3
    entity_threshold: 2
    relation_types: ["cooccurrence", "similarity"]
    top_k: 100  # 图检索也增加数量

# 查询分类器配置 - 启用智能路由
classifier:
  enabled: true
  threshold: 0.5
  classes: ["factual", "analytical", "procedural"]
  adaptation_enabled: true
  min_samples: 10
  performance_threshold: 0.1

fusion:
  method: "weighted"  # 使用加权融合，更适合医疗领域
  weights:
    bm25: 0.5      # 增加BM25权重，医疗术语匹配重要
    dense: 0.4     # 语义理解
    graph: 0.1     # 关系发现
  top_k: 100  # 大幅增加最终结果数量
  rrf_k: 60   # RRF参数

reranker:
  enabled: false  # 暂时关闭，专注于检索优化

evaluation:
  metrics: ["recall@5", "recall@10", "recall@20", "recall@50", "ndcg@10", "ndcg@20", "map", "mrr"]
  output_path: "checkpoints/logs/high_performance_eval_results.json"

system:
  device: "cpu"
  batch_size: 8   # 减小batch size提高质量
  num_threads: 8  # 增加线程数
  log_level: "INFO"
  log_path: "checkpoints/logs/high_performance_system.log"
