# 自适应融合测试配置文件 - SciFact数据集
# 仅使用向量检索和BM25检索，不包含图检索器

dataset: "scifact"

data:
  corpus_path: "data/processed/scifact_corpus.jsonl"
  queries_path: "data/processed/scifact_queries.jsonl"
  qrels_path: "data/processed/scifact_qrels.tsv"

retrievers:
  # 密集向量检索
  dense:
    enabled: true
    model_name: "intfloat/e5-large-v2"
    index_type: "hnsw"
    top_k: 20
    batch_size: 32
    max_length: 512
    normalize_embeddings: true

  # BM25检索
  bm25:
    enabled: true
    k1: 1.2
    b: 0.75
    top_k: 20

  # 图检索 - 禁用
  graph:
    enabled: false

# 自适应融合配置
adaptive_fusion:
  default_method: "weighted_sum"
  available_methods:
    - "weighted_sum"
    - "reciprocal_rank_fusion"
    - "max_score"
    - "min_rank"
    - "score_normalization"
  normalize_scores: true

# 融合配置
fusion:
  method: "weighted_sum"
  weights:
    dense: 0.7
    bm25: 0.3
  rrf_k: 60
  top_k: 10

# 查询分析器配置
query_analyzer:
  semantic_model_name: "intfloat/e5-large-v2"
  spacy_model_name: "en_core_web_sm"
  keyword_query_threshold: 0.7
  semantic_query_threshold: 0.6
  entity_query_threshold: 0.5

# 评估配置
evaluation:
  metrics: ["recall@5", "recall@10", "ndcg@10", "map", "mrr"]
  k_values: [1, 3, 5, 10]

# 系统配置
system:
  device: "cpu"
  batch_size: 16
  num_threads: 4
  log_level: "INFO"

# 实验配置
experiment:
  max_queries: 30  # 限制测试查询数量
  save_intermediate: true
  output_dir: "checkpoints/logs"