# 自适应混合索引配置文件
# 用于配置自适应混合索引系统的各个组件

# 查询分析器配置
query_analyzer:
  # 语义模型配置
  semantic_model_name: "sentence-transformers/all-MiniLM-L6-v2"
  # NLP模型配置
  spacy_model_name: "zh_core_web_sm"
  # 查询类型判断阈值
  keyword_query_threshold: 0.7
  semantic_query_threshold: 0.6
  entity_query_threshold: 0.5
  # 特征提取配置
  min_keyword_length: 2
  max_keywords: 10

# 自适应路由器配置
adaptive_router:
  # 路由策略: 'rule' (基于规则), 'ml' (机器学习), 'hybrid' (混合)
  routing_strategy: "hybrid"
  # 机器学习模型类型
  model_type: "random_forest"  # 'random_forest', 'logistic_regression'
  # 可用融合方法
  available_fusion_methods: 
    - "weighted_sum"
    - "reciprocal_rank_fusion"
    - "max_score"
    - "score_normalization"
  # 默认配置
  default_primary_index: "efficient_vector"
  default_fusion_method: "weighted_sum"
  # 数据存储目录
  data_dir: "data/adaptive_router"

# 自适应融合引擎配置
adaptive_fusion:
  # 默认融合方法
  default_method: "weighted_sum"
  # 可用融合方法
  available_methods:
    - "weighted_sum"
    - "reciprocal_rank_fusion"
    - "max_score"
    - "min_rank"
    - "score_normalization"
  # RRF参数
  rrf_k: 60
  # 是否归一化分数
  normalize_scores: true

# 检索器配置
retrievers:
  # 高效向量索引
  efficient_vector:
    # 嵌入模型
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    # 索引类型: 'hnsw', 'ivf'
    index_type: "hnsw"
    # 是否自动选择索引类型
    auto_index_selection: true
    # 大数据集阈值
    large_dataset_threshold: 1000000
    # HNSW参数
    hnsw_m: 16
    hnsw_ef_construction: 200
    hnsw_ef_search: 128
    # IVF参数
    ivf_nlist: 100
    ivf_nprobe: 10
    # 缓存配置
    cache_dir: "cache/efficient_vector"
  
  # 语义增强BM25
  semantic_bm25:
    # BM25参数
    bm25_k1: 1.5
    bm25_b: 0.75
    # 语义模型
    semantic_model_name: "sentence-transformers/all-MiniLM-L6-v2"
    # 语义权重
    semantic_weight: 0.3
    # 查询扩展
    enable_query_expansion: true
    query_expansion_terms: 3
    query_expansion_weight: 0.5
    # 文档扩展
    enable_document_expansion: true
    document_expansion_terms: 5
    # 缓存配置
    cache_dir: "cache/semantic_bm25"
  
  # 传统BM25
  bm25:
    # BM25参数
    k1: 1.2
    b: 0.75
    # 缓存配置
    cache_dir: "cache/bm25"
  
  # 密集向量检索
  dense:
    # 嵌入模型
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    # 批处理大小
    batch_size: 32
    # 缓存配置
    cache_dir: "cache/dense"
  
  # 图检索
  graph:
    # Neo4j配置
    neo4j_host: "localhost"
    neo4j_port: 7687
    neo4j_username: "neo4j"
    neo4j_password: "password"
    # 实体提取配置
    entity_extraction:
      method: "spacy"
      model_name: "zh_core_web_sm"
    # 关系提取配置
    relation_extraction:
      method: "pattern"
      patterns: ["subj -> obj", "entity -> property"]
    # 缓存配置
    cache_dir: "cache/graph"

# 评估配置
evaluation:
  # 评估指标
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "mrr"
    - "ndcg"
    - "map"
  # k值列表
  k_values: [1, 3, 5, 10, 20]
  # 详细分析
  detailed_analysis: true
  # 分组分析
  group_analysis:
    enabled: true
    groups: ["query_type", "query_length", "entity_count"]

# 实验配置
experiment:
  # 输出目录
  output_dir: "reports/adaptive_experiments"
  # 是否保存中间结果
  save_intermediate: true
  # 是否生成可视化报告
  generate_plots: true
  # 并行处理
  parallel_processing: true
  # 最大并行数
  max_workers: 4

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/adaptive_experiments.log"