# FusionRAG 系统配置文件
# 包含所有新组件的配置

metadata:
  name: "FusionRAG高级配置"
  version: "1.0.0"
  description: "包含所有新组件的FusionRAG系统配置"

# 数据配置
data:
  corpus_path: "data/processed/corpus.jsonl"
  queries_path: "data/processed/queries.jsonl"
  qrels_path: "data/processed/qrels.tsv"
  output_dir: "data/processed"

# 检索器配置
retrievers:
  # BM25检索器
  bm25:
    enabled: true
    top_k: 100
    k1: 1.2
    b: 0.75
    use_cache: true
    cache_dir: "checkpoints/retriever/bm25_cache"
  
  # 稠密向量检索器
  dense:
    enabled: true
    top_k: 100
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    batch_size: 32
    use_gpu: true
    normalize_embeddings: true
    pooling_strategy: "mean"
    cache_dir: "checkpoints/retriever/dense_cache"
  
  # 图检索器
  graph:
    enabled: false  # 默认关闭，需要Neo4j支持
    neo4j_uri: "bolt://localhost:7687"
    neo4j_user: "neo4j"
    neo4j_password: "password"
    max_walk_length: 3
    entity_threshold: 0.5
    relation_threshold: 0.3
    use_cache: true
    cache_dir: "checkpoints/retriever/graph_cache"
  
  # 高效向量索引 (新组件)
  efficient_vector:
    enabled: true
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    index_path: "checkpoints/retriever/efficient_vector_index.faiss"
    index_type: "hnsw"  # 可选: flat, ivf, hnsw
    top_k: 100
    batch_size: 64
    use_gpu: true
    # HNSW参数
    hnsw_m: 16  # 每个节点的最大连接数
    hnsw_ef_construction: 200  # 构建时的搜索宽度
    hnsw_ef_search: 128  # 搜索时的搜索宽度
    # 量化参数
    use_quantization: false  # 是否使用量化
    quantization_bits: 8  # 量化位数
  
  # 语义增强BM25 (新组件)
  semantic_bm25:
    enabled: true
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    index_path: "checkpoints/retriever/semantic_bm25_index.pkl"
    top_k: 100
    k1: 1.2
    b: 0.75
    semantic_weight: 0.5  # 语义相似度权重
    term_weight: 0.5  # 词频权重
    use_cache: true
    cache_dir: "checkpoints/retriever/semantic_bm25_cache"
  
  # 级联检索器 (新组件)
  cascade:
    enabled: true
    first_stage: "bm25"  # 第一阶段检索器
    second_stage: "dense"  # 第二阶段检索器
    first_stage_top_k: 100  # 第一阶段返回的文档数量
    second_stage_top_k: 20  # 第二阶段返回的文档数量
    score_threshold: 0.5  # 第一阶段分数阈值
    use_cache: true
    cache_dir: "checkpoints/retriever/cascade_cache"

# 查询分类器配置
classifier:
  enabled: true
  model_name: "distilbert-base-uncased"
  model_path: "checkpoints/classifier/query_classifier.pt"
  classes: ["factual", "analytical", "procedural"]
  threshold: 0.5
  feature_extractors: ["length", "complexity", "entities", "keywords"]
  adaptation_enabled: true  # 是否启用自适应学习
  adaptation_rate: 0.1  # 自适应学习率

# 融合配置
fusion:
  method: "dynamic"  # 可选: weighted, rrf, combsum, dynamic
  top_k: 20
  # 静态权重配置
  weights:
    bm25: 0.3
    dense: 0.3
    efficient_vector: 0.2
    semantic_bm25: 0.2
  # 动态权重配置
  dynamic_weight_config:
    use_query_classification: true
    class_weights:
      factual:
        bm25: 0.4
        dense: 0.2
        efficient_vector: 0.2
        semantic_bm25: 0.2
      analytical:
        bm25: 0.2
        dense: 0.4
        efficient_vector: 0.2
        semantic_bm25: 0.2
      procedural:
        bm25: 0.3
        dense: 0.3
        efficient_vector: 0.1
        semantic_bm25: 0.3
    fallback_weights:
      bm25: 0.3
      dense: 0.3
      efficient_vector: 0.2
      semantic_bm25: 0.2
  # RRF配置
  rrf_k: 60  # RRF常数

# 评估配置
evaluation:
  metrics: ["recall@5", "recall@10", "ndcg@10", "map", "mrr"]
  output_path: "reports/evaluation"
  save_results: true
  detailed_analysis: true
  per_query_analysis: true

# LLM配置
llm:
  provider: "openai"  # 可选: openai, huggingface, local
  # OpenAI配置
  openai:
    api_key: "${OPENAI_API_KEY}"  # 从环境变量获取
    model: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 1024
  # Hugging Face配置
  huggingface:
    model_name: "google/flan-t5-large"
    use_gpu: true
    max_length: 512
  # 本地模型配置
  local:
    model_path: "checkpoints/llm/local_model"
    tokenizer_path: "checkpoints/llm/local_tokenizer"
    use_gpu: true
    max_length: 512

# 系统配置
system:
  index_name: "fusionrag"
  device: "auto"  # 将自动选择cuda或cpu
  batch_size: 32
  num_threads: 8
  log_level: "INFO"
  log_path: "checkpoints/logs/system.log"
  enable_gpu: true
  cache_enabled: true
  cache_size: 1000
  temp_dir: "checkpoints/temp"