classifier:
  adaptation_enabled: true
  adaptation_rate: 0.1
  classes:
  - factual
  - analytical
  - procedural
  enabled: true
  feature_extractors:
  - length
  - complexity
  - entities
  - keywords
  model_name: distilbert-base-uncased
  model_path: checkpoints/classifier/query_classifier.pt
  threshold: 0.5
data:
  corpus_path: data/processed/nfcorpus_corpus.jsonl
  output_dir: data/processed
  qrels_path: data/processed/nfcorpus_qrels.tsv
  queries_path: data/processed/nfcorpus_queries.jsonl
evaluation:
  detailed_analysis: true
  metrics:
  - recall@5
  - recall@10
  - ndcg@10
  - map
  - mrr
  output_path: reports/evaluation
  per_query_analysis: true
  save_results: true
fusion:
  dynamic_weight_config:
    class_weights:
      analytical:
        bm25: 0.2
        dense: 0.4
        efficient_vector: 0.2
        semantic_bm25: 0.2
      factual:
        bm25: 0.4
        dense: 0.2
        efficient_vector: 0.2
        semantic_bm25: 0.2
      procedural:
        bm25: 0.3
        dense: 0.3
        efficient_vector: 0.1
        semantic_bm25: 0.3
    fallback_weights:
      bm25: 0.3
      dense: 0.3
      efficient_vector: 0.2
      semantic_bm25: 0.2
    use_query_classification: true
  method: dynamic
  rrf_k: 60
  top_k: 20
  weights:
    bm25: 0.3
    dense: 0.3
    efficient_vector: 0.2
    semantic_bm25: 0.2
llm:
  huggingface:
    max_length: 512
    model_name: google/flan-t5-large
    use_gpu: true
  local:
    max_length: 512
    model_path: checkpoints/llm/local_model
    tokenizer_path: checkpoints/llm/local_tokenizer
    use_gpu: true
  openai:
    api_key: ${OPENAI_API_KEY}
    max_tokens: 1024
    model: gpt-3.5-turbo
    temperature: 0.7
  provider: openai
metadata:
  dataset: nfcorpus
  description: 包含所有新组件的FusionRAG系统配置
  name: FusionRAG高级配置
  version: 1.0.0
retrievers:
  bm25:
    b: 0.75
    cache_dir: checkpoints/retriever/bm25_cache
    enabled: true
    k1: 1.2
    top_k: 100
    use_cache: true
  cascade:
    cache_dir: checkpoints/retriever/cascade_cache
    enabled: true
    first_stage: bm25
    first_stage_top_k: 100
    score_threshold: 0.5
    second_stage: dense
    second_stage_top_k: 20
    use_cache: true
  dense:
    batch_size: 32
    cache_dir: checkpoints/retriever/dense_cache
    enabled: true
    model_name: sentence-transformers/all-MiniLM-L6-v2
    normalize_embeddings: true
    pooling_strategy: mean
    top_k: 100
    use_gpu: true
  efficient_vector:
    batch_size: 64
    enabled: true
    hnsw_ef_construction: 200
    hnsw_ef_search: 128
    hnsw_m: 16
    index_path: checkpoints/retriever/efficient_vector_index.faiss
    index_type: hnsw
    model_name: sentence-transformers/all-MiniLM-L6-v2
    quantization_bits: 8
    top_k: 100
    use_gpu: true
    use_quantization: false
  graph:
    cache_dir: checkpoints/retriever/graph_cache
    enabled: false
    entity_threshold: 0.5
    max_walk_length: 3
    neo4j_password: password
    neo4j_uri: bolt://localhost:7687
    neo4j_user: neo4j
    relation_threshold: 0.3
    use_cache: true
  semantic_bm25:
    b: 0.75
    cache_dir: checkpoints/retriever/semantic_bm25_cache
    enabled: true
    index_path: checkpoints/retriever/semantic_bm25_index.pkl
    k1: 1.2
    model_name: sentence-transformers/all-MiniLM-L6-v2
    semantic_weight: 0.5
    term_weight: 0.5
    top_k: 100
    use_cache: true
system:
  batch_size: 32
  cache_enabled: true
  cache_size: 1000
  device: cpu
  enable_gpu: true
  index_name: fusionrag
  log_level: INFO
  log_path: checkpoints/logs/system.log
  num_threads: 8
  temp_dir: checkpoints/temp
